[tool.commitizen]
name = "cz_conventional_commits"
version = "0.4.0"
version_files = [
    ".cz.toml:version",
    "package.json:version",
]
changelog_file = "CHANGELOG.md"
update_changelog_on_bump = true
